# Generated by Django 5.0.4 on 2025-03-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
