# Generated by Django 5.0.4 on 2025-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0002_rename_create_at_carro_created_at'),
        ('productos', '0004_rename_imagen_producto_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carro_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carro',
            name='productos',
            field=models.ManyToManyField(to='productos.producto'),
        ),
    ]
