# Generated by Django 5.0.4 on 2025-01-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(default='', upload_to='productos/'),
            preserve_default=False,
        ),
    ]
